### ISSUE TITLE
create pkcli.cd that deploys with twine

### ISSUE THREAD

**Issue by cchall** [radiasoft/pykern#113]
The pykern version installed from PyPI dates back to June.

**Comment by robnagler** [comment]
In the meantime, @cchall could you update the instructions for rsopt to pip install from git? I think we'll add something for weekly releases, but this will fix the issue.

**Comment by cchall** [comment]
I went ahead an updated the rsopt instructions just in case, though I'm not aware of any issues with pykern versioning and rsopt. I actually ran into this while writing some code for middl and just thought I would point it out since it briefly confused me when `pip install pykern --upgrade` didn't do what I expected.

**Comment by robnagler** [comment]
We need to figure out the install_requires issues. tox may be necessary to run tests in environments. twine is the way people push to pypi, but it shouldn't be done via pksetup.py or tox.

**Comment by robnagler** [comment]
Using pyproject, twine gone.
