### ISSUE TITLE
pkio.sorted_glob recursive

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#123]
py35 added support for the `recursive` kwarg [to glob](https://docs.python.org/3.7/library/glob.html#glob.glob). It allows searching subdirectories. 

[Raydata has a use](https://github.com/radiasoft/sirepo/blob/8fc2eb26b77980929cd5ba6bc5328f55a20c7895/sirepo/template/raydata.py#L53) for this.

I'm working on radiasoft/sirepo#2431 and it has a use too.

So, I think it is worth adding to pkio

**Comment by robnagler** [comment]
I think we can just implement recursive under the covers. There are no cases where '**' is used so we can just set recursive=true on the glob calls. We may want to use iglob under the covers, too. sorted_glob can't be an iterator, but it can use an iterator.
