### ISSUE TITLE
add release label to pkcli.github.issue_*

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#129]
We will need to add release to the test repo.

**Comment by rorour** [comment]
@robnagler I need a bit more info to get started- what is a release label?

**Comment by robnagler** [comment]
When we create [a release issue](https://github.com/radiasoft/pykern/blob/d4b37ffce72288bd596393ed9cb05f797e16e7b0/pykern/pkcli/github.py#L561) (also [here](https://github.com/radiasoft/pykern/blob/d4b37ffce72288bd596393ed9cb05f797e16e7b0/pykern/pkcli/github.py#L128)), it should get a label called [release](https://github.com/radiasoft/sirepo/labels/release). It would be good to share the code so add a `_create_release_issue` as a private function that encapsulates adding the label.
