### ISSUE TITLE
Doc & Link PR comments in Design Hints

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#145]
[DesignHints](https://github.com/radiasoft/pykern/wiki/DesignHints) needs to be a living doc. It should also be actively referenced.

Consider https://github.com/radiasoft/sirepo/pull/4211/files#r834910862. We don't have a hint about testing at all in DesignHints so something should be written. What? I think Test What Might Break applies here. Do not test Scooby Doo value, but test that we got a models back at all. That's explained clearly. 

Another Hint might be: Quality Test Failures Output. While it is valid to use an assert, it's not as useful as using `get` in `pkok`, which will produce a nicely formatted message giving a hint as to why the test broke.

I think we should refer back to PRs to give context to the DesignHint. Sometimes I use forward links to DesignHints, but I backlinks to PRs would be useful, too, since Wikis don't provide backlinks automatically (unlike Issues). 

@rorour I'm picking on you so that you since I've written some longer comments recently. You can close this issue once you have documented three hints. @gurhar1133 you are welcome to write some, too, as well as other team members. I am going to add a PR checklist that will include "Any DesignHints?"

Related:
- [Test Everything That Could Break](https://wiki.c2.com/?TestEverythingThatCouldPossiblyBreak) 
- [Recent hacker news exchange](https://news.ycombinator.com/item?id=23893484))
- [The Psychology of Software Testing](https://www.robnagler.com/2008/02/03/The-Psychology-of-Software-Testing.html)

**Comment by rorour** [comment]
@robnagler I added Test What Might Break and Quality Test Failures Output.  I’m struggling to think of any more on my own. PR reviews are teaching me a lot, but I don’t think I have this level of insight for design yet.

I cleaned up some broken links and spelling. Also, the Ensure Loops Exit example doesn’t exit— should it be `i >= 0` instead of `i <= 0`? Actually, `i>0` seems more consistent with the first loop in the example.

**Comment by e-carlin** [comment]
https://github.com/radiasoft/pykern/wiki/DesignHints/_compare/df68bddae6e206b89398e94892b442eda6c8175e...6c37bcdb4e2357b22536ab1418e752f277e6bd96
 
@robnagler I'd like you to add two design hints. One is "don't distribute knowledge". You've said it to me many times and I think I get the concept but I tried to write a hint for it and couldn't describe it well. So I guess I don't understand it that well. Second, when to use constants vs not. We've talked about when you use them but I don't remember your reasoning. I never know when to use a constant or not in our code.

**Comment by robnagler** [comment]
There is the [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter), but that's not quite right, and frankly, I don't agree with it all that much. Dynamic languages like Python don't hide anything so it's better to be clear what's public and private, then to enforce some stronger principle.

I could find no reference on this subject, which surprises me. I'm sure I've read stuff about it. I certainly didn't make it up.

The principle is information hiding. However, it's refined by the concept of public and private interfaces, which were unknown when [the original article was published](http://sunnyday.mit.edu/16.355/parnas-criteria.html). The idea is that a module/interface/whatever has public entry points for a reason: to provide function. The rest should be hidden unless something needs that function. At that point you should ask the question: what information does the client need? It's usually not as simple as making a private interface public. That's often what happens, but I think it needs to be conscious choice of what you are exposing. The less exposed, the more decoupled the interface, and the easier it is to modify the private parts of the module. This is about maintenance, not about anything purist.

Constants are a way of explicitly coupling code. I personally like them and use them whenever a constant is public so it provides a coupling. Sometimes, this is hard to do, and I still define the constant, but it may still be defined elsewhere. An example of this is the `'login'` route, because it is defined in JSON in the schema, which is not directly reachable. That opens a can of worms of how you get to it, and what name it has (the route itself). I think in this case it should be asserted that it is indeed a route, which it is in the moderation code.

Sometimes I'm lazy, and I don't use constants. Call me out on that. :)

Nice related article that nobody seems to follow any more: https://martinfowler.com/ieeeSoftware/published.pdf

**Comment by robnagler** [comment]
@rorour writes:
> @robnagler I added Test What Might Break and Quality Test Failures Output. I’m struggling to think of any more on my own. PR reviews are teaching me a lot, but I don’t think I have this level of insight for design yet.

That's great, thanks.

> I cleaned up some broken links and spelling. Also, the Ensure Loops Exit example doesn’t exit— should it be i >= 0 instead of i <= 0? Actually, i>0 seems more consistent with the first loop in the example.

Good catch. All robnagler-conditionals are subject to robnagler-inversion-syndrome(tm).
