### ISSUE TITLE
move xlsx conversion from pkunit.case_dirs to file_eq

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#155]
The [xlsx to csv file conversion](https://github.com/radiasoft/pykern/blob/253ff7fa844d592cd544e2961036d27f51f05faa/pykern/pkunit.py#L107) should move to file_eq. The test cases should move, too.

The code in file_eq could use some modularization into nested functions, too.

**Comment by gurhar1133** [comment]
@robnagler could you provide a little more info about how you would like tests modified?

**Comment by robnagler** [comment]
I think what I meant is that pkunit1_test.py should get test cases for this feature. Bonus points for fixing rsaccounting tests if they break (they shouldn't if the refactoring is done right). I don't think there's anything using the file_eq except rsaccounting.
