### ISSUE TITLE
pkcli docstring printing too greedy

### ISSUE THREAD

**Issue by jeinstei** [radiasoft/pykern#156]
When using the `pkcli` interaction with the middl project, I'm finding that the help printing seems a bit too greedy, printing the entire docstring instead of just the function summary. The command is below:

```bash
(middl) [joshec@roentgen middl]$ middlsoft train -h
usage: middlsoft train [-h] {regressor,vrae} ...
positional arguments:
  {regressor,vrae}
    regressor       Train and run regressor to map latent space back to data
                    Args: configuration (str): path to configuration file in
                    model directory no_cuda (bool): whether or not to use
                    CUDA. Defaults to False. cuda_device (int): CUDA device
                    index. Defaults to -1 (all). do_write (bool): write
                    regressor output to file. Defaults to False. use_sklearn
                    (bool): use scikit-learn MLPRegressor vs pytorch. Defaults
                    to False. datadir (str): alternative directory to find
                    data in. Defaults to None. profile (bool): perform simple
                    profiling of pytorch model. Defaults to False. Returns:
                    None
    vrae
optional arguments:
  -h, --help        show this help message and exit
```

This printing occurs on the disvae_losses branch of the middl project: [middl/middlsoft/pkcli/train.py](https://github.com/radiasoft/middl/blob/d8ebd67e8dff4ff563fc7be78220f785c1fb5ad3/middlsoft/pkcli/train.py#L253-L274)

**Comment by jeinstei** [comment]
I can also rewrite my help to be based on argparse using decorators, but it seems like there's competing documentation standards then.

I'll use whichever is "standard" for us

**Comment by robnagler** [comment]
The standard is Google doc. To be clear, you would like to see:

```txt
$ middlsoft train -h
usage: middlsoft train [-h] {regressor,vrae} ...
commands:
    regressor       Train and run regressor to map latent space back to data
    vrae                <first line of docstring>
```

@gurhar1133 This is generated by `argh` a third party library. It may be we can configure `argh` or we might have to rewrite the error message for this case.

**Comment by gurhar1133** [comment]
If you called 
``` middlsoft train  regressor -h```
Would you want to see the entire docstring for regressor? Or just subject line here as well?

**Comment by robnagler** [comment]
Whole doc string when it is a specific function. I think that works that way now.

**Comment by gurhar1133** [comment]
> Whole doc string when it is a specific function. I think that works that way now.

Cool, yes. Just wanted to see if you wanted that changed as well

How does this look to you:

```
$ pykern projex -h
usage: pykern projex [-h] {init-rs-tree,init-tree} ...

positional arguments:
  {init-rs-tree,init-tree}
    init-rs-tree        Initialize defaults for RadiaSoft project tree and
                        call `init_tree`
    init-tree           Setup a project tree with: docs, tests, etc., and
                        checkin to git.

optional arguments:
  -h, --help            show this help message and exit
```
should ```positional arguments``` be ```commands```?

**Comment by robnagler** [comment]
Looks great!

Yes, positional arguments should be commands.
