### ISSUE TITLE
syntax for 'pykern projex' has changed

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/pykern#16]
As a result, the instructions here
   https://github.com/radiasoft/pykern/wiki/CreatePythonProject
are broken

It seems the 'init-rs-tree' option is gone, so one must use 'init-tree'
However, it is (seemingly) impossible to satisfy the demands of 'init-tree'
As a result, I don't know how to correct the instructions in the wiki

**Comment by robnagler** [comment]
What happens when you enter `pykern projex`, e.g.

```
$ pykern projex
usage: pykern projex [-h] {init-rs-tree,init-tree} ...
pykern projex: error: too few arguments
```

**Comment by bruhwiler** [comment]
I just realized I was working in an old container.
I did the following:
> pip install pip --upgrade
> pip install pykern --upgrade (failed with errors related to setuptools)
> pip install setuptools --upgrade
> pip install pykern --upgrade

Then the init-rs-tree keyword was recognized and things worked as before.

Sorry for the bother.
David
