### ISSUE TITLE
Update wiki/TestingScientificCodes

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/pykern#167]
According to the wiki, 'pytest' should be replaced by 'pykern pytest'
https://github.com/radiasoft/pykern/wiki/TestingScientificCodes

However, 'pykern pytest' seems to call py.test
which seems to have been deprecated to just invoke pytest,
https://github.com/radiasoft/pykern/blob/af25f23c878953e67fddd99912c138d5ad2591da/pykern/pkcli/pytest.py#L11-L13

**Comment by robnagler** [comment]
The correct command is `pykern test`. The documentation is out of date in a number of ways.

**Comment by robnagler** [comment]
@gurhar1133  not a rush, but this needs quite a bit of cleanup. pkmath is pkexample. Remove pkcli/pytest.py. Update for qualified imports. Etc.

**Comment by robnagler** [comment]
You can also say `pykern test .` or `pykern test some_test.py other_test.py`.
