### ISSUE TITLE
20221207 projex upgrade

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#185]
setup.py files need to be updated to
- strip out python 2.7
- probably 'Development Status' is wrong too
- Figure out the minimal set of classifiers
- qualified imports

**Comment by robnagler** [comment]
A new repo filled in by init-tree fails ci. This should be fixed, too.

**Comment by rorour** [comment]
> strip out python 2.7

What needs to be removed aside from `from __future__` in projex jinjas?

> probably 'Development Status' is wrong too

What should it be changed to?

> Figure out the minimal set of classifiers

Could you expand on how to figure this out? The classifiers in setup.py.jinja seem pretty minimal to me.

> qualified imports

Could you expand on where/how to do this?

**Comment by robnagler** [comment]
I'm not sure what pyhon 2.7 stuff is in there, but maybe `u"""`. 

I don't know anything about classifier requirements. Do some research on them. Maybe see if PyPI has a set of required.

These should go:
>         'Programming Language :: Python :: 3',
>        'Programming Language :: Python :: 3.7',

I don't know that Topic, audience, etc. is really necessary. Maybe pre-alpha is fine for development

unqualified imports eg.

> from pykern import pksetup

should be import pykern.pksetup.

**Comment by rorour** [comment]
Classifiers are entirely optional. They're just "used by community members to find projects based on their desired criteria". Are there any that you want to keep?

**Comment by robnagler** [comment]
Could you look at some popular projects and see what they do?

**Comment by robnagler** [comment]
@rorour please remove .travis.yml as well.
