### ISSUE TITLE
Add black formatter to pykern test

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#186]
This needs to be written to find all code and test python files that aren't test data or package_data and then run black on them. (Maybe black can do this already.)

pykern test would look for a file (perhaps) or an environment variable to determine whether it should run black.  

If there are differences between the formatted and unformatted file, pykern test would fail with an error.

**Comment by gurhar1133** [comment]
After playing around with this a little I've found a couple things:

1) in`pkcli/sim.py` line 220:
```python
f.chmod(0600)
```
triggers this error `error: cannot format /home/vagrant/src/radiasoft/pykern/pykern/pkcli/sim.py: cannot use --safe with this file; failed to parse source file AST: invalid token (<unknown>, line 220)`. Suggestions?

2) If I comment that line out and run fmt.check() on the pykern repo it will tell me `error: path=/home/vagrant/src/radiasoft/pykern needs to be formatted`. I am guessing we want to report each specific file within a repo that needs reformatting?

**Comment by robnagler** [comment]
That's interesting. Maybe related to: https://bugzilla.redhat.com/show_bug.cgi?id=1838452

Have you run the formatter on the whole pykern repo?

**Comment by gurhar1133** [comment]
If I comment that line out then I can run the formatter on the entire repo. 

The line in question also gets highlighted by my editor, maybe because of the leading 0 in `f.chmod(0600)`?

Should I edit fmt module to avoid formatting package_data and test_data or should that be done in pykern test?

**Comment by gurhar1133** [comment]
Oh, and again, we want to list every file that would be reformatted right?

**Comment by robnagler** [comment]
> The line in question also gets highlighted by my editor, maybe because of the leading 0 in f.chmod(0600)?

Change it to `0o600`.

> Should I edit fmt module to avoid formatting package_data and test_data or should that be done in pykern test?

That's a good question. Should our python templates be formatted? The jinja templates won't be found. There's only one file which will be found in package_data: template/elegant/lib/SCRIPT-commandFile.combine.py 

The _work and _data directories should not be found. fmt should import pkunit and pkunit should export _data and _work. There's code in test.py that implements the exclusion in its search. I was just working on that for #198 (PR #199). Once you approve the PR, you can add the pkunit change to export DATA_DIR (work_dir exported in #199).

**Comment by gurhar1133** [comment]
@robnagler 
We dont want
```bash
pykern ci run .
error: path=. needs to be formatted
```
right? 

In `ci.py`, should `fmt.check(path)` be run on the entire tree and all failed checks get saved to output so which know which paths need formatting?

**Comment by robnagler** [comment]
The CI runs in a docker container which is destroyed. The only saved output goes to stdout and stderr. I suggest we just output there. 

> error: path=. needs to be formatted

This is sort of ok, but not great. Maybe you could run diff instead of check? That way it might output the diffs to stdout?

**Comment by gurhar1133** [comment]
Diff is a good idea
