### ISSUE TITLE
Remove script dir from sys.path?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#203]
Try this from any directory (not in sys.path):

```
echo 'import csv;csv.reader' > csv.py
python csv.py
```

It will give this error: `AttributeError: module 'csv' has no attribute 'reader'`

@garsuga ran into this error, and I was confused by it. I now see that sys.path gets PWD inserted. This broke @garsuga's code that we had to stop using the program, because sirepo.numpy exists. (The program cd'd to the module being debugged, which is a separate issue.)

I think we should consider dropping the first element in sys.path in pykern.pkcli. (We should also add a fixup to projex that imports everything unqualified to reduce [but not eliminate] collisions.)

This has been [known in Unix since 1984](https://people.engr.ncsu.edu/gjin2/Classes/246/Spring2019/Security.pdf). 

Go recently [added something to prevent this](https://github.com/golang/go/issues/43724). I think this is a breaking change.

Since all processes are started with pykern.pkcli.main (except sirepo_jupyterhub which could be changed), it could strip '.' from the first element of sys.path. I think this would avoid problems and be more secure.

**Comment by e-carlin** [comment]
Sounds good. FWIW they've added a flag and env var in 3.11 https://github.com/python/cpython/pull/31542

**Comment by robnagler** [comment]
Thanks for the link @e-carlin. It led me to [_PyPathConfig_ComputeSysPath0](https://github.com/python/cpython/blob/38af903506e9b18c6350c1dadcb489f057713f36/Python/pathconfig.c#L376), which computes syspath0. The function with documentation is 142 lines long. More importantly it uses readlink. Furthermore, py.test inserts pwd in sys.path. Kind of messy.
