### ISSUE TITLE
pykern.import_on_use

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#207]
[ImportThoughts](https://github.com/radiasoft/pykern/wiki/ImportThoughts) has the motivation, but the solution could be simpler. 

The use would be:
import pykern

pykern.import_on_use('''
    pykern.pkdebug pkdp
    sirepo.simulation_db
''')

The implementation is complicated but not much more than PKDict. import_on_use would would assign an object to the names: pkdp, sirepo, and simulation_db. When these names were referenced, they'd look for the library with importlib and then assign the found objects to the module attributes, thus removing the import_on_use proxy object.

**Comment by e-carlin** [comment]
I think this will break typing across modules with tools like mypy, lsp, etc. They don't speak `pykern.import_on_use` so they won't know that a name like `pykern.pkdebug` which was created through `import_on_use` is really referring to a module.

**Comment by robnagler** [comment]
Agreed. It's the wrong direction.
