### ISSUE TITLE
reformat code in DesignHints and other wikis

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#209]
This could be an interesting project. Not sure how much code is out there, but running pkcli.fmt on the individual snippets would be cool. Kind of a spare time thing (one page at a time).

**Comment by gurhar1133** [comment]
Maybe this issue should involve some basic documentation of the fmt interface @robnagler?

**Comment by robnagler** [comment]
Make that a separate issue.

**Comment by gurhar1133** [comment]
@robnagler reformatted design hints, should go through all the other pykern wikis as well?

**Comment by robnagler** [comment]
Yes, please.

**Comment by robnagler** [comment]
Some are outdated so they may not be worth updating. See if you can note which ones are outdated.

**Comment by gurhar1133** [comment]
I formatted other areas. I couldn't find outdated stuff, but some of the pages were things I know very little about. Like [here](https://github.com/radiasoft/pykern/wiki/ImportThoughts) and [here](https://github.com/radiasoft/pykern/wiki/Mockup)
