### ISSUE TITLE
On travis: ImportError: No module named download

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#23]
If you look at the [previous build](https://travis-ci.org/radiasoft/pykern/builds/331087076), it's got the same version of `pip`, but it doesn't get this error:

```text
$ python --version
Python 2.7.14
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages (python 2.7)
install.1
$ pip install setuptools==32.1.3
$ python setup.py pkdeploy
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from pykern.pksetup import setup
  File "/home/travis/build/radiasoft/pykern/pykern/pksetup.py", line 51, in <module>
    import pip.download
ImportError: No module named download
```

**Comment by robnagler** [comment]
Looks like the moved pip.download to pip._internal.download. From the [Release Notes](https://pip.pypa.io/en/stable/news):

> Move all of pip's APIs into the pip._internal package, properly reflecting the fact that pip does not currently have any public APIs. (#4696, #4700)

We use pip to parse requirements.txt so we'll change that to whatever is recommended.

**Comment by robnagler** [comment]
@slacAWallace Please try the last step again. Thanks.

**Comment by slacAWallace** [comment]
Yes that seemed to do the trick. Install was successful.
