### ISSUE TITLE
GitHub Action verification that HEAD's SHA has passed all actions

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#234]
There needs to be a way of checking github to see if HEAD has passed ci-pull-request workflow. Maybe there's a way to search actions via an API. The goal is to ask the question before a release: has HEAD passed CI?

**Comment by rorour** [comment]
Where should this check be added? I think I've got the api part figured out, but not sure if I should write this in bash script or something else

**Comment by robnagler** [comment]
If it is bash, that's fine, or could be added as a function to pkcli.github.
