### ISSUE TITLE
pykern fmt "usability"

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#240]
These are my own personal preferences so if there is disagreement I'm happy to use bash aliases:)

1. fmt should be default_command in pykern.pkcli.fmt so I can just say `pykern fmt`
2. cwd should be the default dir. Again so I can say `pykern fmt` and everything at ./ and below will be fmt'ed.

**Comment by moellep** [comment]
If we had a default command, you wouldn't be able to query the module for the list of commands. And if you typed "pykern fmt" thinking you would get a list of commands, it would instead be destructive from your current directory.

**Comment by e-carlin** [comment]
You could say `pykern fmt --help` to query for the commands. But I think the concern about doing something destructive unintentionally is fair.

**Comment by robnagler** [comment]
I am less of a fan of "default" commands these days. If you ever need to extend the module, you're stuck with changing the api.

**Comment by e-carlin** [comment]
Makes sense. Thanks both for weighing in.
