### ISSUE TITLE
fmt documentation

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/pykern#245]
fmt interface needs documentation.

**Comment by robnagler** [comment]
It is more devops than design hints. I think we should put it radiasoft/devops/wiki. Maybe add a Developer page?

**Comment by gurhar1133** [comment]
[Here's](https://github.com/radiasoft/devops/wiki/Developer) a start. Should I document pkcli.ci here as well?

**Comment by robnagler** [comment]
Looks good (briefly). When you first reference pkcli.fmt, call it pykern.pkcli.format, and link to the master commit of it.

**Comment by gurhar1133** [comment]
Take another look at [docs](https://github.com/radiasoft/devops/wiki/Developer) ?

**Comment by robnagler** [comment]
I changed the first part to be passive and simpler. See if you can pattern the rest of the doc similarly.

**Comment by gurhar1133** [comment]
K, think I did it
