### ISSUE TITLE
add pkcli.message for output that is not an error but a warning or info

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#251]
This would be similar to command_error without the exception. The message would go to stderr.

**Comment by Rootie2shoes** [comment]
Amazon Web Services | "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/demo-branch"
-- | --
Azure | repo:octo-org/octo-repo:ref:refs/heads/demo-branch
Google Cloud Platform | (assertion.sub=='repo:octo-org/octo-repo:ref:refs/heads/demo-branch')
HashiCorp Vault | bound_subject="repo:octo-org/octo-repo:ref:refs/heads/demo-branch
