### ISSUE TITLE
20221031 Update style guide to use Base as the standard class name            

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#270]
If a module consists solely of a class, then the module is the primary descriptor and the class should be named `Base`. Add description and text to pykern.pkexample.

**Comment by mkeilman** [comment]
Does this still apply if the module contains subclasses of `Base`? Should such a thing be discouraged? What about private `_Base` as in `xslx.py`? It has both private and public subclasses

**Comment by robnagler** [comment]
This is a very specific rule: module is the class, that is, Base is exported, and the name of the module defines the meaning of Base. This is to prevent [rsdockerspawner.rsdockerspawner.RSDocker](https://github.com/radiasoft/rsdockerspawner/blob/b1364e7e741ee24fa31185b743728640691b273d/rsdockerspawner/rsdockerspawner.py#L63).  RSConf components all match this rule. I used T, which I would replace with Base when I have the time.

This is not about a module which has multiple classes or private classes, etc.
