### ISSUE TITLE
20221115 Change "error" to "check_prints error"

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#307]
```bash
$ echo "# i am a comment with print('foo')" > x.py
$ pykern ci check_prints
error: x.py:1 # i am a comment with print('foo')
```

I think the _PRINT_OK regex should be changed
from: `^\s*#\s*(?:pkdp|print)\(`
to: `^\s*#.*(?:pkdp|print)\(` (There can be any characters after `#` not just whitespace)

The command error should say where the error is coming from (what function). When it is run in `pykern ci run` the reader has no clue where the error is coming from (see https://github.com/radiasoft/rsconf/actions/runs/3292642290/jobs/5428245294 for example).

**Comment by robnagler** [comment]
I agree about the error reporting. I don't agree about the regex change. The point of the comment is to comment out a print or pkdp statement, i.e. commenting out legit code. Putting print() in our code is never legit.

A "POSIT" is not executable code. Rather, it is an explicit coupling. This would be a better comment:

```py
# POSIT: databroker.catalog_search_path()
```
