### ISSUE TITLE
20221130 add ci check for modules with main programs

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#313]
madx_device_server is an example of this. Only "main" should be in `<project>`_console.py.

**Comment by rorour** [comment]
Should this only apply to sirepo?

**Comment by robnagler** [comment]
This applies to all repos that are setup with pkcli's. We should always write pkcli's so they are reusable/testable/modular and live in exactly one place in the repo.

**Comment by rorour** [comment]
Checking for `def main` or `__main__`, pykern fails the check:

```
error: check_main: pykern/pkcli/__init__.py:118 def main(root_pkg, argv=None):
pykern/pkcli/ci.py:42 _MAIN = re.compile(r"def main\b|__main__")
pykern/pkconfig.py:258                 "pkconfig.init() called from __main__; cannot configure, ignoring",
pykern/pkinspect.py:82     Note: may return __main__ module.
pykern/pkinspect.py:84     Will raise exception if calling from __main__
pykern/pkinspect.py:113         # Will raise exception if calling from __main__
pykern/pkinspect.py:130     Note: may return __main__ module.
pykern/pkinspect.py:132     Will raise exception if calling from __main__
pykern/pkinspect.py:144     """Is the caller's calling module __main__?
pykern/pkinspect.py:147         bool: True if calling module was called by __main__.
pykern/pkinspect.py:149     return caller_module().__name__ == "__main__"
pykern/pkresource.py:109     if "__main__" in packages:
pykern/pksetup.py:340             def main():
pykern/pksetup.py:440                 # TODO(robnagler): assert that 'def main()' exists in python module

```

pykern/pkcli/__init__.py contains a main function. Most of the rest are part of multiline comments. Should I exclude instances that are part of comments and specifically exclude pykern/pkcli/?

> This applies to all repos that are setup with pkcli's.

I'm confused about what this means. If we have ci set up on a repo, won't this run regardless of whether that repo has its own pkcli directory? I'm wondering about this in context of what you said on a previous PR:

> We are going to run this on all repos, eventually. The scientists want to implement CI.

Will scientists have to remove all instances of main in order to pass ci, or will this check not be run on all repos? Or will we be adding a lot of exceptions to this check?

**Comment by robnagler** [comment]
`def main` is probably ok. It's this line (or switched order test):

```py
if __name__ == "__main__":
```

I think it would be safe to test for a regexp of `r'^if.*__name__'`. Python enforces indentation so it's going to be at the outermost level in 99% of the cases we want to catch.

> if we have ci set up on a repo, won't this run regardless of whether that repo has its own pkcli directory?

Correct, good point.

> Will scientists have to remove all instances of main in order to pass ci, or will this check not be run on all repos? Or will we be adding a lot of exceptions to this check?

Interestingly I have a question about dev standards from @gurhar1133... I think we have our `ci` standard, which is reasonable and discussed (and changeable with more discussion, of course). If people want to use `ci`, they get it. Just like people using `black` get those opinions.

**Comment by rorour** [comment]
is this IRD?

**Comment by robnagler** [comment]
Yes, assigned.
