### ISSUE TITLE
20221213 ci check_prints should only look in <pkg> and tests directories

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#329]
https://github.com/radiasoft/rshellweg/pull/141 is failing because prints are found, but they were there all along. I wonder if something changed.

I think we may want to change the way check_prints and check_main is started. It should only run on the tests and `<pkg>`, e.g. sirepo, directories. I'm wondering if we don't want the same rule for fmt as well. Thoughts?

**Comment by rorour** [comment]
> https://github.com/radiasoft/rshellweg/pull/141 is failing because prints are found, but they were there all along. I wonder if something changed.

I don't see an example of the failing files ever passing ci. It looks like ci was not run on [the commit where they were added](https://github.com/radiasoft/rshellweg/commit/a77a192410e16f428de509d972d1674b55986fbf)...not sure why that happened.

I agree with changing to only run on those directories.

**Comment by robnagler** [comment]
We can just call check_prints and check_main within specific directories from ci, but still allow people to run them from other directories. ci can check for the package root by the repo name (that's our convention) so it should be an easy fix.

**Comment by robnagler** [comment]
This holding up the PR so if you could spend time on this tomorrow that would be great.

**Comment by rorour** [comment]
Is there any reason not to include check_eof_newline in this change?

**Comment by robnagler** [comment]
Correct. It should be. We should include setup.py and README.md and maybe others(?) in the root directory. They should have newlines at EOF.

**Comment by robnagler** [comment]
Still getting failures https://github.com/radiasoft/rshellweg/actions/runs/3689719112/jobs/6370440733#step:3:141 because fmt needs the same paths that check_prints uses. It doesn't need the walk tree, just pass `_paths()`. I'm not sure pkcli.fmt accepts multiple paths so it may need to be adapted.

**Comment by robnagler** [comment]
@rorour please test against rshellweg before submitting a PR.
