### ISSUE TITLE
text line reader

### ISSUE THREAD

**Issue by moellep** [radiasoft/pykern#33]
It would be nice to have a pkio.io text reader methd which went line by line, rather than reading the whole file into memory with read_text(). Maybe with a callback function by line. Something like:
```
    with io.open(str(path), encoding=locale.getpreferredencoding()) as f:
        for num, line in enumerate(f):
            callback(line, num)
```

**Comment by robnagler** [comment]
Is it for size reasons or do you need a line-by-line for parsing reasons? We could use a generator if it is size, and return a list, if not.

**Comment by moellep** [comment]
It is for size reasons - some data files can be gigabytes.

**Comment by robnagler** [comment]
Is enumerate necessary? If we create a generator, then you can:

```py
for num, line in enumerate(pkio.read_lines(path)):
      do something
```

**Comment by robnagler** [comment]
The implementation for the above would be better:

```py
def open_text(path):
    return io.open(str(fn), encoding=locale.getpreferredencoding())
```

It is slightly problematic, because you would have to use a with:

```py
with pkio.open_text(path) as f:
     for l in f:
         do something
```

**Comment by moellep** [comment]
Any implementation is fine as long as the whole file isn't read into memory and the line numbers can be computed in some way.
