### ISSUE TITLE
py3: Exception doesn't stringify "in"?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#34]
@njsmith I was wondering if you know anything about this. I'm trying to get pykern py3 compatible.

In py.test, this form works in py2:

```py
    with pytest.raises(argh.CommandError) as e:
        pkcli.command_error('{abc}', abc='abcdef')
    assert 'abcdef' in e.value, \
        'When passed a format, command_error should output formatted result'
```

But it fails in py3 with: `TypeError: argument of type 'CommandError' is not iterable`. 

I wrote this test, which gets the same error:

```py
from __future__ import print_function
import argh
try:
    raise argh.CommandError('foo')
except Exception as e:
    assert 'foo' in e
```

CommandError is a simple subclass of Exception. This works in py2, but something changed in py3, which I can't find quickly. The work around in this case is to `str(e)`, but it might be something that I don't understand about `in` in py3 vs py2.

**Comment by njsmith** [comment]
Huh, I didn't know this. Apparently in py2, exceptions act like a sequence of their args – you can index and iterate over `exc`, and it's the same as indexing or iterating over `exc.args`:

```python
>>> exc = RuntimeError("foo", "bar")
>>> exc[0]
'foo'
>>> list(exc)
['foo', 'bar']
>>> "foo" in exc
True
```

It's *not* auto-stringification:

```python
>>> "f" in exc
False
```

It's also not a complete implementation of the sequence protocol:

```python
>>> len(exc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'exceptions.RuntimeError' has no len()
```

This strikes me as kinda weird and I'm not surprised it got cleaned up in py3.

Anyway, for py3 compatibility, I think you can mechanically replace `obj in exc` with `obj in exc.args`.

**Comment by robnagler** [comment]
Thanks for looking into this @njsmith.
