### ISSUE TITLE
python setup.py <anything> is deprecated

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#37]
https://github.com/pypa/setuptools/issues/1684 talks about deprecating `python setup.py test` and all other arguments. The plan is to use tox, which we use for testing, but it's unwieldy for other things, like deployment.

Migrate the code out of pysetup into another tool that supports deployment, documentation, etc.

Read the docs build process should be looked, because it calls python setup.py. Perhaps there's a way to just call an arbitrary command or have setup.py do that instead. see https://github.com/rtfd/readthedocs.org/tree/master/readthedocs/doc_builder

See https://github.com/jaraco/skeleton

**Comment by jeinstei** [comment]
Given this deprecation, doing a local user install of a module wouldn't work unless the pip metadata was somehow included as well?

In short, pykern-enabled modules REQUIRE installation using pip? I haven't seen anything in a lot of the package guides on how to programaticaly block this using functions in setup.py, but there has to be some way.

**Comment by robnagler** [comment]
The point of this issue is to move out testing and doc generation from setup.py. Not a rush, because I doubt it will come through.

Installation via pip is not required. Just make sure that `python setup.py` is run at some point.

**Comment by robnagler** [comment]
https://github.com/radiasoft/pykern/issues/466
