### ISSUE TITLE
Generalize srdb._init_root

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#405]
[_init_root](https://github.com/radiasoft/sirepo/blob/51f5712a9f812ce9abab9a0ffccef80a2613ad2c/sirepo/srdb.py#L51) does a lot of work, which could be generalized to something like pykern.util.init_db_dir and .cfg_db_dir (cfg parser).

**Comment by gurhar1133** [comment]
@robnagler what do you recommend for the generalized version of the check in srdb._init_root():
```python
# Check to see if we are in our dev directory. This is a hack,
# but should be reliable.
if not r.join("requirements.txt").check():
        # Don't run from an install directory
        r = pkio.py_path(".")
```
https://github.com/radiasoft/sirepo/blob/51f5712a9f812ce9abab9a0ffccef80a2613ad2c/sirepo/srdb.py#L76-L80

Another hack like checking for "README" or "MANIFEST" or "LISCENCE"? or something else?

**Comment by robnagler** [comment]
We can check for either setup.py or pyproject.toml. README, MANIFEST, and test aren't strong enough. setup.py is weaker than pyproject.toml, but good enough for our environment.
