### ISSUE TITLE
delete pkcollections.json_load_any

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#407]
pkcollection.object_pairs_hooks should stay. json_load_any should be moved into pkjson. 

Depends on https://github.com/radiasoft/sirepo/issues/6442

**Comment by rorour** [comment]
the only use of pkcollections.json_load_any that I see outside of pykern & sirepo is in jupyter_rs_radia.

https://github.com/radiasoft/jupyter_rs_radia/blob/ae1d0c5010210f80c24a8c9e099605c15edaef6b/jupyter_rs_radia/radia_viewer.py#L218

Is that repo still in use/worth updating?

**Comment by robnagler** [comment]
Yes, it's important to update.
