### ISSUE TITLE
github_bkp silence errors related to missing wiki for non radiasoft repos

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#415]
In https://github.com/radiasoft/pykern/pull/376 we fixed silencing of errors for repos that have no wiki. But, the [regex test](https://github.com/radiasoft/pykern/blob/aff64cd690713836e84acd4b75e18590afa15f5b/pykern/pkcli/github.py#L31) we use is too restrictive. It checks for only "radiasoft" wikis. We need to handle non-rs wikis too (ex biviosoftware). 

Let's relax the regex to allow for any org/user. I think we can change the regex to look for `[\w-\.]+` for both the username and repo name https://stackoverflow.com/a/59082561.

@Benbenbenin0 not the highest priority issue but can you get to it in the next week or so?

**Comment by Benbenbenin0** [comment]
@e-carlin Sure thing I'll get started on this
