### ISSUE TITLE
Improve case_dirs/file_eq doc

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#417]
Please write something. Doesn't need to be long, just a start.

@Benbenbenin0 writes:
> I went to the [testing wiki](https://github.com/radiasoft/pykern/wiki/Testing#case_dirs) in pykern to learn more about pkunit, I would probably add it in one of two locations:
> 
> The case_dir section after discussing where the expected files are located (.out)
> The file_eq section after discussing what kind of comparisons are possible.

I wrote:
BTW, the typical way to generate test data with case dirs (and this should be documented) is to touch the file, e.g. touch 20210331_ptd.csv (in appropriate out directory), and let the test show you the differences. The test will also output a command to correct the data. This is easier and as reliable as having to generate the csv yourself.

It would be nice to document this somewhere. If you see an obvious place, let me know.

**Comment by Benbenbenin0** [comment]
@robnagler Added the following to [case_dir wiki](https://github.com/radiasoft/pykern/wiki/Testing#case_dirs):

"To generate expect files for testing, touch the file in the appropriate .out directory. The test will show you the differences and output a command to correct the data. This is easier and more reliable than generating the file yourself."

**Comment by robnagler** [comment]
Thanks!
