### ISSUE TITLE
pkjson.dump_pretty as pkcli

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#437]
It would be convenient to run something like `pykern fmt json <filename>` and have filename formatted using pkjson.dump_pretty.

This brings up the question of whether we should add json formatting to our ci checks?

**Comment by e-carlin** [comment]
Or maybe just `pykern fmt run <filename>` and have it figure out that it is json.

**Comment by robnagler** [comment]
rely on jq
