### ISSUE TITLE
Update version of black

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#450]
It's pinned now to 22, but we should go to 24. @rorour do you remember more about b94654cad337332bc69afdda088c049be5362f46?

**Comment by rorour** [comment]
I think we only pinned the version to prevent chaos with them changing formatting standards with every version. https://github.com/radiasoft/sirepo/pull/5295#issuecomment-1365606303

**Comment by rorour** [comment]
I had forgotten my role as the Black Sentry. https://github.com/radiasoft/ops/wiki/Open-Source-Sentries
I can take this issue

**Comment by robnagler** [comment]
Thanks. See how drastic the differences are, and we can coordinate an update.
