### ISSUE TITLE
More flexible dict()

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#5]
Perhaps this exists somewhere in Python libraries, but documenting here. I want this for a dictionary:

* d.pkdel('x') - does not raise a key error if 'x does not exist
* d.pksetdefault('x', some_func) - calls some_func to init if executable else init with value
* d.some_key = val - refer to keys as attributes if have underscore in the middle or camelcase
* this.pkmerge(that) - recursively merge d and 
* this.pkimport(json) - initialize from json/yaml/etc.
* this.pkexport(json) - convert back to json/yaml/etc.

**Comment by robnagler** [comment]
I added pkcollections.Dict and pkcollections.json_load_any. json_load_any passes `object_pairs_hook=Dict` so that you can now refer to attributes like you can in Javascript, that is, by referring to them as attributes. There is an assertion that any `dict` attrs cannot be set as values on `Dict`, but that's a small set with a low collision set, especially given that we are defaulting to camelCase values.

Why do this? I think `data.models.beamline[4].position` is clearer than `data['models']['beamline'][4]['position']`. That's conjecture, but I think it is worth a try...

**Comment by moellep** [comment]
This change breaks elegant where many keys are not camelCase and correspond
directly to elegant field names, like "k". "values" and "items" also
collide.

**Comment by robnagler** [comment]
"k" is ok. It's values and items that collide.

Maybe it's a bad idea, but I think it might be worth trying to avoid
collisions.
