### ISSUE TITLE
tornado.httpclient.AsyncHTTPClient causing unbounded growth in number of open sockets

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/pykern#529]
Creating [a reference to an instance of AsyncHTTPClient](https://github.com/radiasoft/pykern/blob/8894b7c9c9f3c1f09772dc09123404e4bb794f11/pykern/http.py#L151) is causing unbounded growth in the number of open sockets. Eventually we run out of file descriptors. I opened an issue in Tornado about this https://github.com/tornadoweb/tornado/issues/3424. As a stop gap I'm going to re-structure our HTTPClient code to remove storing the reference in self._client which should fix the issue.

**Comment by e-carlin** [comment]
[Ben letft a great response to my issue](https://github.com/tornadoweb/tornado/issues/3424). Obvious now that he points it out. The instantiation of the client and the use of the client happen in different event loops. Our solution is effectively the one he suggested (run under a function marked async so we will be in the asyncio.run event loop). 

So, keep the fix but note that my reasoning for why it was a fix was flawed.

**Comment by robnagler** [comment]
We really should fix the code to not use asyncio.run

**Comment by e-carlin** [comment]
Make the whole job cmd async or something else?

**Comment by robnagler** [comment]
Yes, I think it might also help with this branch https://github.com/radiasoft/sirepo/tree/6784-fastcgi-improve

job_cmd should be async, and it should send messages, not jsonl via stdout. There too many problems with this.
