### ISSUE TITLE
poll github ratelimit code in sleep

### ISSUE THREAD

**Issue by robnagler** [radiasoft/pykern#94]
github returns strange numbers:

```txt
trying max sleep; X-RateLimit-Reset=1614013796 > 4000 + now=1613838365
```

That's too long. It's supposed to be an hour. 

https://docs.github.com/en/rest/reference/rate-limit#get-rate-limit-status-for-the-authenticated-user

**Comment by robnagler** [comment]
@e-carlin do you think we need this?

**Comment by e-carlin** [comment]
I'm not sure. I haven't tested it. Want me to and report back?

**Comment by robnagler** [comment]
Lets not do this, because the bigger thing was incremental issues (#93), which reduces our apis to under 5K and get done in 45 mins.
